### ISSUE TITLE
如何设置远程服务器的ip地址呢？

### ISSUE THREAD

**Issue by luckypoem** [wdongxv/DDDProxy#2]
hi.
我看了localServer.py文件（https://github.com/wdongxv/DDDProxy/blob/master/localServer.py），没有发现设置远程服务器的ip地址的地方，那么如何设置远程服务器的ip地址呢？

**Comment by wdongxv** [comment]
运行后，用浏览器打开http://127.0.0.1:8080

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:dddproxy brite$ python localServer.py
start server on: :8080
Traceback (most recent call last):
  File "localServer.py", line 36, in <module>
    server.start()
  File "/Users/yuming/dddproxy/DDDProxy/baseServer.py", line 373, in start
    self.onSocketEvent(sock, sockConnect.socketEventCanRecv)
  File "/Users/yuming/dddproxy/DDDProxy/baseServer.py", line 397, in onSocketEvent
    connect.onSocketEvent(event)
  File "/Users/yuming/dddproxy/DDDProxy/baseServer.py", line 220, in onSocketEvent
    self._onReadyRecv()
  File "/Users/yuming/dddproxy/DDDProxy/baseServer.py", line 202, in _onReadyRecv
    self.onRecv(data)
  File "/Users/yuming/dddproxy/DDDProxy/localProxyServerHandler.py", line 54, in onRecv
    connect = localToRemoteConnectManger.getConnect()
  File "/Users/yuming/dddproxy/DDDProxy/localToRemoteConnectManger.py", line 117, in getConnect
    return localToRemoteConnectManger.manager.get()
  File "/Users/yuming/dddproxy/DDDProxy/localToRemoteConnectManger.py", line 68, in get
    if self.remoteConnectListLoop >= len(remoteServerList)*maxConnectByOnServer:
TypeError: object of type 'NoneType' has no len()
yudeMacBook-Air:dddproxy brite$

怎么解决问题？

**Comment by wdongxv** [comment]
你好，刚刚已经修复了，更新下试试

**Comment by luckypoem** [comment]
hi.

yudeMacBook-Air:dddproxy yuming$ git pull
remote: Counting objects: 75, done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 75 (delta 32), reused 24 (delta 24), pack-reused 30
Unpacking objects: 100% (75/75), done.
From https://github.com/wdongxv/DDDProxy
   95d563b..d745571  master     -> origin/master
   8fca6dc..f57b4b6  asyncIO    -> origin/asyncIO
Updating 95d563b..d745571
Fast-forward
 .pydevproject                            |  2 +-
 DDDProxy/baseServer.py                   |  7 +++++--
 DDDProxy/domainConfig.py                 | 10 ++++++++--
 DDDProxy/localProxyServerHandler.py      | 12 +++++++-----
 DDDProxy/localToRemoteConnectManger.py   |  6 ++++--
 DDDProxy/symmetryConnectServerHandler.py | 17 +++++++++--------
 DDDProxy/template/index.html             |  5 +++--
 DDDProxy/template/pac.js                 | 23 ++++++++++++++++++-----
 DDDProxy/version.py                      | 10 ++++++++++
 localServer.py                           | 14 ++++++++++----
 macx/install.sh                          | 20 ++++++++++++++++++++
 macx/restart.sh                          |  7 +++++++
 readme.md                                |  2 +-
 13 files changed, 103 insertions(+), 32 deletions(-)
 create mode 100644 DDDProxy/version.py
 create mode 100755 macx/install.sh
 create mode 100755 macx/restart.sh
yudeMacBook-Air:dddproxy yuming$ ls
DDDProxy    localServer.py  macx        readme.md   remoteServer.py
yudeMacBook-Air:dddproxy yuming$ python localServer.py
start server on: :8080
Already up-to-date.

但是还是翻不了墙啊。

**Comment by luckypoem** [comment]
hi.

你还是未回答我的问题：
“我看了localServer.py文件（https://github.com/wdongxv/DDDProxy/blob/master/localServer.py），没有发现设置远程服务器的ip地址的地方，那么如何设置远程服务器的ip地址呢？”啊。

可否答复下呢？
非常感谢！

**Comment by luckypoem** [comment]
hi。

感觉完全不需要远程服务器似的，那怎么翻得了墙呢？

**Comment by wdongxv** [comment]
https://github.com/wdongxv/DDDProxy#如何运行
